(()=>{
'use strict';
const SAVE='bannerMilesSave_v2';
const BASE_CRUISE=.42;
const TICK=100;

const beaches=[
{id:'driftwood',name:'Driftwood Beach',unlock:0,avg:400,desc:'Cheap motels, fishing pier, and long quiet stretches.',rates:[.02,.04],weights:[20,70],zones:[['Quiet Shore',150],['Motel Strip',350],['Fishing Pier',650],['Public Beach',900],['Quiet Shore',200]]},
{id:'pelican',name:'Pelican Point',unlock:50,avg:700,desc:'A small tourist beach with a growing summer crowd.',rates:[.03,.06],weights:[40,100],zones:[['Beach Houses',350],['Marina',700],['Hotel Row',950],['Public Beach',1200],['Coastal Road',500]]},
{id:'boardwalk',name:'Boardwalk Bay',unlock:250,avg:1400,desc:'Hotels, restaurants, rides, and a busy boardwalk.',rates:[.05,.09],weights:[70,150],zones:[['Condos',800],['Boardwalk',1800],['Amusement Pier',2400],['Hotel District',1600],['Open Beach',1000]]},
{id:'sunset',name:'Sunset Shores',unlock:1000,avg:2400,desc:'A large vacation destination with steady crowds.',rates:[.08,.14],weights:[110,220],zones:[['Vacation Homes',1400],['Resort Strip',2800],['Public Beach',3600],['Restaurant Row',2500],['South Shore',1700]]},
{id:'palm',name:'Palm Harbor',unlock:5000,avg:4800,desc:'Packed resorts, marina traffic, and premium advertisers.',rates:[.12,.22],weights:[170,320],zones:[['Marina',3000],['Resort Beach',5600],['Convention Hotel',7000],['Shopping District',4700],['North Beach',3500]]},
{id:'coral',name:'Coral City',unlock:15000,avg:8500,desc:'A full coastal city with towers and year-round visitors.',rates:[.18,.32],weights:[250,430],zones:[['Harbor',5000],['High-Rise Coast',9000],['City Beach',12500],['Entertainment Strip',10800],['Outer Coast',6200]]},
{id:'grand',name:'Grand Coast',unlock:40000,avg:15000,desc:'A major destination packed with national brands.',rates:[.28,.50],weights:[350,580],zones:[['Resort Towers',10500],['Festival Beach',22000],['Boardwalk Core',25000],['Hotel Canyon',14500],['Yacht Harbor',12000]]},
{id:'golden',name:'Golden Strand',unlock:100000,avg:28000,desc:'The final beach: huge crowds, luxury resorts, and major advertisers.',rates:[.45,.80],weights:[500,750],zones:[['Luxury Marina',18000],['Golden Boardwalk',32000],['Mega Resort',42000],['Event Beach',50000],['Skyline Coast',26000]]}
];
const advertiserNames=[
["Benny's Bait & Ice",'Driftwood Pizza','Pier 9 Tackle',"Lou's Beach Dogs",'Seaside Mini Golf',"Captain Joe's Seafood"],
['Pelican Surf Shop','Point Realty','Salty Cone Ice Cream','Harbor Grill','Wave Rider Rentals','Pelican Inn'],
['Boardwalk Arcade','Neon Crab Shack','Bayview Hotels','Coaster Pier','Boardwalk Outfitters','Sunset Soda'],
['Sunset Resorts','Coastal Motors','Shoreline Brewing','VacationNow','Ocean Club','Sunset Concert Series'],
['Palm Harbor Resort','Bluewater Casino','Coastline Bank','Marina Marketplace','Palm Air Tours','Golden Tan Sunscreen'],
['Coral City Hotels','Atlantic Wireless','Coral Energy','Metro Motors','Oceanfront Live','Coastal Credit'],
['Grand Coast Resorts','National Cola','SunWave Mobile','Grand Coast Racing','Liberty Insurance','American Beachwear'],
['Golden Strand Casino','National Resorts','Apex Motors','Skyline Financial','Victory Sports','Continental Wireless']
];
const branches=[
{id:'power',name:'Power',desc:'Tow heavier banners and increase cruise speed.',nodes:[['p1','Engine Tune-Up',75,'Capacity 35 / 65 / 95 lb',{capacity:[35,65,95],speed:1.08}],['p2','Carburetor Rebuild',250,'Capacity 50 / 90 / 125 lb',{capacity:[50,90,125],speed:1.08}],['p3','New Propeller',900,'Capacity 70 / 125 / 170 lb',{capacity:[70,125,170],speed:1.09}],['p4','Cylinder Overhaul',3000,'Capacity 100 / 175 / 235 lb',{capacity:[100,175,235],speed:1.10}],['p5','Performance Exhaust',12000,'Capacity 140 / 245 / 325 lb',{capacity:[140,245,325],speed:1.11}],['p6','High-Compression Engine',50000,'Capacity 195 / 345 / 450 lb',{capacity:[195,345,450],speed:1.12}],['p7','Heavy Tow Package',220000,'Capacity 265 / 485 / 625 lb',{capacity:[265,485,625],speed:1.13}],['p8','Coastal Performance Engine',1200000,'Capacity 355 / 665 / 850 lb',{capacity:[355,665,850],speed:1.15}]]},
{id:'fuel',name:'Fuel',desc:'Increase range.',nodes:[['f1','Patched Fuel Tank',100,'MED range 5 miles',{range:5}],['f2','Larger Tank',300,'MED range 8 miles',{range:8}],['f3','New Fuel System',1000,'MED range 13 miles',{range:13}],['f4','Auxiliary Tank',4000,'MED range 22 miles',{range:22}],['f5','Extended Tank',15000,'MED range 35 miles',{range:35}],['f6','Long-Range Tank',60000,'MED range 55 miles',{range:55}],['f7','Extended Fuel System',250000,'MED range 85 miles',{range:85}],['f8','Endurance Fuel System',1000000,'MED range 130 miles',{range:130}]]},
{id:'efficiency',name:'Efficiency',desc:'Use less fuel.',nodes:[['e1','Seal the Cowling',150,'5% less fuel used',{efficiency:.05}],['e2','Balance the Prop',500,'5% less fuel used',{efficiency:.05}],['e3','Streamlined Tow Cable',1500,'7% less fuel used',{efficiency:.07}],['e4','Weight Reduction',6000,'8% less fuel used',{efficiency:.08}],['e5','Cleaner Airframe',25000,'10% less fuel used',{efficiency:.10}],['e6','Cruise Tuning',100000,'12% less fuel used',{efficiency:.12}],['e7','Precision Fuel System',450000,'15% less fuel used',{efficiency:.15}]]},
{id:'advertising',name:'Advertising',desc:'Reach more people.',nodes:[['a1','Clean Banner Rig',125,'+5% people reached',{audience:.05}],['a2','Better Banner Position',450,'+7% people reached',{audience:.07}],['a3','Local Reputation',1800,'+8% people reached',{audience:.08}],['a4','Prime Tow Position',7500,'+10% people reached',{audience:.10}],['a5','Regional Reputation',30000,'+12% people reached',{audience:.12}],['a6','Premium Advertising',125000,'+15% people reached',{audience:.15}],['a7','National Reputation',600000,'+20% people reached',{audience:.20}]]}
];

const fresh=()=>({money:0,careerMiles:0,currentBeach:0,purchased:[],contract:null,offers:[],totalPeople:0,flights:0,currentPage:'playPage'});
let state=load(); let flight=null; let lastTick=0; let toastTimer=0;
const $=id=>document.getElementById(id);
const el={cash:$('cashValue'),career:$('careerMilesValue'),beach:$('beachValue'),contract:$('contractValue'),fuelText:$('fuelText'),fuelBar:$('fuelBar'),distance:$('distanceValue'),people:$('peopleValue'),earnings:$('flightEarningsValue'),banner:$('banner'),zone:$('zoneName'),crowd:$('crowdRate'),flightButton:$('flightButton'),scene:$('scene'),buildingTrack:$('buildingTrack'),beachTrack:$('beachTrack'),activeContract:$('activeContractCard'),contracts:$('contractsGrid'),refresh:$('refreshContractsButton'),upgrades:$('upgradeTree'),beaches:$('beachGrid'),stats:$('statsGrid'),reset:$('resetButton'),pages:[...document.querySelectorAll('.page')],nav:[...document.querySelectorAll('.bottom-nav button')]};

function load(){try{return {...fresh(),...JSON.parse(localStorage.getItem(SAVE)||'{}')}}catch{return fresh()}}
function save(){localStorage.setItem(SAVE,JSON.stringify(state))}
function money(v){if(v<1000)return '$'+Math.round(v).toLocaleString();for(const [s,d] of [['T',1e12],['B',1e9],['M',1e6],['K',1e3]])if(v>=d)return '$'+(v/d).toFixed(v>=d*100?0:v>=d*10?1:2)+s;return '$'+Math.round(v).toLocaleString()}
const num=v=>Math.floor(v).toLocaleString(); const has=id=>state.purchased.includes(id);
function planeStats(){let capacity=[25,50,75],baseRange=3,speed=1,efficiency=0,audience=0;for(const b of branches)for(const n of b.nodes)if(has(n[0])){const e=n[4];if(e.capacity)capacity=e.capacity;if(e.range)baseRange=e.range;if(e.speed)speed*=e.speed;if(e.efficiency)efficiency+=e.efficiency;if(e.audience)audience+=e.audience}return{capacity,baseRange,speed,efficiency:Math.min(.62,efficiency),audience}}
function weightClass(w){const[min,med,max]=planeStats().capacity;if(w>max)return{key:'locked',label:'TOO HEAVY',fuel:Infinity};if(w<=min)return{key:'light',label:'LIGHT',fuel:.9};if(w<=med)return{key:'good',label:'MED - IDEAL',fuel:1};return{key:'heavy',label:'HEAVY',fuel:1.3}}
function rangeFor(w){const s=planeStats(),c=weightClass(w);return Number.isFinite(c.fuel)?s.baseRange/(c.fuel*(1-s.efficiency)):0}
function stage(){const n=state.purchased.length;return n>=27?5:n>=21?4:n>=13?3:n>=6?2:1}
function unlockedCount(){return beaches.filter(b=>state.careerMiles>=b.unlock).length}
function nextBeach(){return beaches.find(b=>state.careerMiles<b.unlock)}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}

function generateOffers(){if(state.contract||flight)return;const bi=state.currentBeach,b=beaches[bi],pool=advertiserNames[bi],out=[],used=new Set(),max=planeStats().capacity[2];while(out.length<3){const ni=Math.floor(Math.random()*pool.length);if(used.has(ni))continue;used.add(ni);let weight=Math.round(b.weights[0]+(b.weights[1]-b.weights[0])*(.1+Math.random()*.82));const rate=b.rates[0]+(b.rates[1]-b.rates[0])*Math.random(),flights=3+Math.floor(Math.random()*Math.min(8,2+bi));out.push({id:`${Date.now()}_${ni}_${out.length}`,business:pool[ni],beachIndex:bi,weight,rate:+rate.toFixed(3),flightsTotal:flights,flightsRemaining:flights})}
  if(!out.some(o=>o.weight<=max) && b.weights[0]<=max) out[0].weight=Math.max(b.weights[0],Math.floor(max*.85));
  state.offers=out;save();
}
function accept(id){if(state.contract||flight)return;const o=state.offers.find(x=>x.id===id);if(!o)return;if(weightClass(o.weight).key==='locked'){toast('That banner is above your current MAX tow weight.');return}state.contract={...o};state.offers=[];state.currentPage='playPage';save();render();toast(`${o.business} contract accepted.`)}
function startFlight(){if(!state.contract||flight)return;const r=rangeFor(state.contract.weight);if(!r)return;flight={distance:0,people:0,earnings:0,fuel:100,range:r};lastTick=performance.now();state.currentPage='playPage';render();requestAnimationFrame(tick)}
function endFlight(reason='manual'){if(!flight)return;const f=flight;flight=null;lastTick=0;const before=unlockedCount();state.money+=f.earnings;state.careerMiles+=f.distance;state.totalPeople+=f.people;state.flights++;if(state.contract){state.contract.flightsRemaining--;if(state.contract.flightsRemaining<=0){const name=state.contract.business;state.contract=null;generateOffers();toast(`${name} contract complete.`)}else toast(`${reason==='fuel'?'Fuel exhausted.':'Flight ended.'} ${state.contract.flightsRemaining} flight${state.contract.flightsRemaining===1?'':'s'} remaining.`)}const after=unlockedCount();if(after>before)toast(`${beaches[after-1].name} unlocked!`);save();render()}
function tick(now){if(!flight)return;const dt=Math.min(.25,(now-lastTick)/1000);lastTick=now;const s=planeStats(),miles=BASE_CRUISE*s.speed*dt;flight.distance+=miles;flight.fuel=Math.max(0,100*(1-flight.distance/flight.range));const b=beaches[state.currentBeach],zone=b.zones[Math.floor(flight.distance/1.2)%b.zones.length],pulse=.92+Math.sin(now/850)*.08+Math.sin(now/2900)*.05,reached=miles*zone[1]*(1+s.audience)*pulse;flight.people+=Math.max(0,reached);flight.earnings=flight.people*state.contract.rate;renderFlight(zone);moveScene();if(flight.fuel<=.001){endFlight('fuel');return}setTimeout(()=>requestAnimationFrame(tick),TICK)}

function buy(id){if(flight)return;for(const b of branches){const i=b.nodes.findIndex(n=>n[0]===id);if(i<0)continue;const n=b.nodes[i];if(has(id)||i>0&&!has(b.nodes[i-1][0]))return;if(state.money<n[2]){toast(`You need ${money(n[2]-state.money)} more.`);return}state.money-=n[2];state.purchased.push(id);save();render();toast(`${n[1]} installed.`);return}}
function travel(i){if(flight||state.contract){toast(state.contract?'Finish the current contract before changing beaches.':'End the flight before changing beaches.');return}if(state.careerMiles<beaches[i].unlock)return;state.currentBeach=i;state.offers=[];generateOffers();save();buildScene();render();toast(`Now flying over ${beaches[i].name}.`)}
function setPage(id){state.currentPage=id;save();el.pages.forEach(p=>p.classList.toggle('active',p.id===id));el.nav.forEach(b=>b.classList.toggle('active',b.dataset.page===id))}

function buildScene(){el.buildingTrack.innerHTML='';const palette=['tan','blue','coral','green','tan','gold','blue','coral','green','tan'];const heights=[72,104,86,126,94,145,80,112,92,132];for(let repeat=0;repeat<3;repeat++)for(let i=0;i<palette.length;i++){const d=document.createElement('div');d.className=`hotel ${palette[i]}`;d.style.width=(52+(i%4)*13)+'px';d.style.height=(heights[i]+state.currentBeach*4)+'px';el.buildingTrack.appendChild(d)}
  el.beachTrack.innerHTML='';const items=['umbrella','person','person orange','umbrella blue','person green','umbrella yellow','person dark','person','umbrella green','person orange','person green','umbrella','person dark','umbrella blue','person'];for(let repeat=0;repeat<4;repeat++)for(const cls of items){const d=document.createElement('div');d.className=cls;el.beachTrack.appendChild(d)}
}
function moveScene(){const d=flight?flight.distance:0;el.buildingTrack.style.transform=`translateX(${-(d*32)%720}px)`;el.beachTrack.style.transform=`translateX(${-(d*72)%950}px)`}
function renderTop(){el.cash.textContent=money(state.money);el.career.textContent=state.careerMiles.toFixed(1)+' mi';el.beach.textContent=beaches[state.currentBeach].name;el.contract.textContent=state.contract?`${state.contract.business} (${state.contract.flightsRemaining}/${state.contract.flightsTotal})`:'None';el.scene.className=`scene stage-${stage()}${flight?' flying':''}`;el.banner.textContent=state.contract?state.contract.business.toUpperCase():'NO CONTRACT';if(flight){el.flightButton.textContent='End Flight';el.flightButton.classList.add('danger');el.flightButton.disabled=false}else if(state.contract){el.flightButton.textContent='Start Flight';el.flightButton.classList.remove('danger');el.flightButton.disabled=false}else{el.flightButton.textContent='Choose a Contract';el.flightButton.classList.remove('danger');el.flightButton.disabled=true}}
function renderFlight(zoneOverride){const z=zoneOverride||beaches[state.currentBeach].zones[0];if(!flight){el.fuelText.textContent='100%';el.fuelBar.style.width='100%';el.distance.textContent='0.00 mi';el.people.textContent='0';el.earnings.textContent='$0';moveScene()}else{el.fuelText.textContent=`${flight.fuel.toFixed(0)}%`;el.fuelBar.style.width=`${flight.fuel}%`;el.distance.textContent=`${flight.distance.toFixed(2)} mi`;el.people.textContent=num(flight.people);el.earnings.textContent=money(flight.earnings)}el.zone.textContent=z[0];el.crowd.textContent=`${num(z[1])} people / mile`}
function renderActive(){if(!state.contract){el.activeContract.innerHTML='<h3>No active contract</h3><div class="meta">Choose an offer below. Start the flight from the Play screen.</div>';return}const wc=weightClass(state.contract.weight);el.activeContract.innerHTML=`<h3>${state.contract.business}</h3><div class="meta">Pay: <strong>$${state.contract.rate.toFixed(3)}/person</strong> &nbsp; Weight: <strong>${state.contract.weight} lb</strong> <span class="tag ${wc.key}">${wc.label}</span><br>Flights remaining: <strong>${state.contract.flightsRemaining}/${state.contract.flightsTotal}</strong></div>`}
function renderOffers(){if(!state.offers.length&&!state.contract)generateOffers();el.contracts.innerHTML='';for(const o of state.offers){const wc=weightClass(o.weight),card=document.createElement('article');card.className='card';card.innerHTML=`<h3>${o.business}</h3><div class="meta">$${o.rate.toFixed(3)}/person<br>${o.weight} lb <span class="tag ${wc.key}">${wc.label}</span><br>${o.flightsTotal} flights</div><button type="button" ${wc.key==='locked'?'disabled':''}>Accept Contract</button>`;card.querySelector('button').addEventListener('click',()=>accept(o.id));el.contracts.appendChild(card)}if(!state.offers.length&&state.contract)el.contracts.innerHTML='<article class="card"><div class="meta">Finish the current contract to receive new offers.</div></article>'}
function renderUpgrades(){el.upgrades.innerHTML='';for(const b of branches){const branch=document.createElement('section');branch.className='branch';branch.innerHTML=`<h3>${b.name}</h3><p>${b.desc}</p>`;b.nodes.forEach((n,i)=>{const bought=has(n[0]),prior=i===0||has(b.nodes[i-1][0]),u=document.createElement('div');u.className=`upgrade ${bought?'bought':''}`;u.innerHTML=`<h4>${n[1]}</h4><small>${money(n[2])} - ${n[3]}</small><button type="button" ${bought||!prior||state.money<n[2]||flight?'disabled':''}>${bought?'Bought':'Buy'}</button>`;u.querySelector('button').addEventListener('click',()=>buy(n[0]));branch.appendChild(u)});el.upgrades.appendChild(branch)}}
function renderBeaches(){el.beaches.innerHTML='';beaches.forEach((b,i)=>{const unlocked=state.careerMiles>=b.unlock,current=i===state.currentBeach,c=document.createElement('article');c.className='card';c.innerHTML=`<h3>${b.name}</h3><div class="meta">Unlock: ${num(b.unlock)} career miles<br>Average: ${num(b.avg)} people/mile<br>${b.desc}</div><button type="button" ${!unlocked||current?'disabled':''}>${current?'Current Beach':'Travel Here'}</button>`;c.querySelector('button').addEventListener('click',()=>travel(i));el.beaches.appendChild(c)})}
function renderStats(){const s=planeStats(),next=nextBeach();el.stats.innerHTML=`<div class="statcard"><span>Total Flights</span><strong>${num(state.flights)}</strong></div><div class="statcard"><span>Total People</span><strong>${num(state.totalPeople)}</strong></div><div class="statcard"><span>Plane Stage</span><strong>${stage()}</strong></div><div class="statcard"><span>Next Beach</span><strong>${next?next.name:'All unlocked'}</strong></div><div class="statcard"><span>MIN / MED / MAX</span><strong>${s.capacity.join(' / ')}</strong></div><div class="statcard"><span>MED Range</span><strong>${(s.baseRange/(1-s.efficiency)).toFixed(1)} mi</strong></div>`}
function render(){renderTop();renderFlight();renderActive();renderOffers();renderUpgrades();renderBeaches();renderStats();setPage(state.currentPage||'playPage')}

function hook(){document.addEventListener('dblclick',e=>e.preventDefault());let lastTouch=0;document.addEventListener('touchend',e=>{const now=Date.now();if(now-lastTouch<350)e.preventDefault();lastTouch=now},{passive:false});document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});el.flightButton.addEventListener('click',()=>{if(flight)endFlight('manual');else if(state.contract)startFlight();else setPage('contractsPage')});el.refresh.addEventListener('click',()=>{if(state.contract||flight){toast('Finish the current contract first.');return}state.offers=[];generateOffers();renderOffers();toast('New offers ready.')});el.reset.addEventListener('click',()=>{if(!confirm('Reset all Banner Miles progress?'))return;localStorage.removeItem(SAVE);state=fresh();flight=null;generateOffers();buildScene();render()});el.nav.forEach(b=>b.addEventListener('click',()=>setPage(b.dataset.page)))}

hook();if(!state.offers.length&&!state.contract)generateOffers();buildScene();render();
})();
