(()=>{
'use strict';
const SAVE='bannerMilesSave_v1',TICK=100;
const beaches=[
{id:'driftwood',name:'Driftwood Beach',unlock:0,avg:400,desc:'Cheap motels, fishing pier, and long quiet stretches.',rates:[.02,.04],weights:[20,70],zones:[['Quiet Shore',150],['Motel Strip',350],['Fishing Pier',650],['Public Beach',900],['Quiet Shore',200]]},
{id:'pelican',name:'Pelican Point',unlock:50,avg:700,desc:'A small tourist beach with a growing summer crowd.',rates:[.03,.06],weights:[40,100],zones:[['Beach Houses',350],['Marina',700],['Hotel Row',950],['Public Beach',1200],['Coastal Road',500]]},
{id:'boardwalk',name:'Boardwalk Bay',unlock:250,avg:1400,desc:'Hotels, restaurants, rides, and a busy boardwalk.',rates:[.05,.09],weights:[70,150],zones:[['Condos',800],['Boardwalk',1800],['Amusement Pier',2400],['Hotel District',1600],['Open Beach',1000]]},
{id:'sunset',name:'Sunset Shores',unlock:1000,avg:2400,desc:'A large vacation destination with steady crowds.',rates:[.08,.14],weights:[110,220],zones:[['Vacation Homes',1400],['Resort Strip',2800],['Public Beach',3600],['Restaurant Row',2500],['South Shore',1700]]},
{id:'palm',name:'Palm Harbor',unlock:5000,avg:4800,desc:'Packed resorts, marina traffic, and premium advertisers.',rates:[.12,.22],weights:[170,320],zones:[['Marina',3000],['Resort Beach',5600],['Convention Hotel',7000],['Shopping District',4700],['North Beach',3500]]},
{id:'coral',name:'Coral City',unlock:15000,avg:8500,desc:'A full coastal city with towers and year-round visitors.',rates:[.18,.32],weights:[250,430],zones:[['Harbor',5000],['High-Rise Coast',9000],['City Beach',12500],['Entertainment Strip',10800],['Outer Coast',6200]]},
{id:'grand',name:'Grand Coast',unlock:40000,avg:15000,desc:'A major destination packed with national brands.',rates:[.28,.50],weights:[350,580],zones:[['Resort Towers',10500],['Festival Beach',22000],['Boardwalk Core',25000],['Hotel Canyon',14500],['Yacht Harbor',12000]]},
{id:'golden',name:'Golden Strand',unlock:100000,avg:28000,desc:'The final beach: huge crowds, luxury resorts, and major advertisers.',rates:[.45,.80],weights:[500,750],zones:[['Luxury Marina',18000],['Golden Boardwalk',32000],['Mega Resort',42000],['Event Beach',50000],['Skyline Coast',26000]]}
];
const names=[
["Benny's Bait & Ice",'Driftwood Pizza','Pier 9 Tackle',"Lou's Beach Dogs",'Seaside Mini Golf',"Captain Joe's Seafood"],
['Pelican Surf Shop','Point Realty','Salty Cone Ice Cream','Harbor Grill','Wave Rider Rentals','Pelican Inn'],
['Boardwalk Arcade','Neon Crab Shack','Bayview Hotels','Coaster Pier','Boardwalk Outfitters','Sunset Soda'],
['Sunset Resorts','Coastal Motors','Shoreline Brewing','VacationNow','Ocean Club','Sunset Concert Series'],
['Palm Harbor Resort','Bluewater Casino','Coastline Bank','Marina Marketplace','Palm Air Tours','Golden Tan Sunscreen'],
['Coral City Hotels','Atlantic Wireless','Coral Energy','Metro Motors','Oceanfront Live','Coastal Credit'],
['Grand Coast Resorts','National Cola','SunWave Mobile','Grand Coast Racing','Liberty Insurance','American Beachwear'],
['Golden Strand Casino','National Resorts','Apex Motors','Skyline Financial','Victory Sports','Continental Wireless']
];
const branches=[
{id:'power',name:'Power',desc:'Tow heavier banners and increase cruise speed.',nodes:[
['p1','Engine Tune-Up',75,'Capacity 35 / 65 / 95 lb',{capacity:[35,65,95],speed:1.08}],
['p2','Carburetor Rebuild',250,'Capacity 50 / 90 / 125 lb',{capacity:[50,90,125],speed:1.08}],
['p3','New Propeller',900,'Capacity 70 / 125 / 170 lb',{capacity:[70,125,170],speed:1.09}],
['p4','Cylinder Overhaul',3000,'Capacity 100 / 175 / 235 lb',{capacity:[100,175,235],speed:1.10}],
['p5','Performance Exhaust',12000,'Capacity 140 / 245 / 325 lb',{capacity:[140,245,325],speed:1.11}],
['p6','High-Compression Engine',50000,'Capacity 195 / 345 / 450 lb',{capacity:[195,345,450],speed:1.12}],
['p7','Heavy Tow Package',220000,'Capacity 265 / 485 / 625 lb',{capacity:[265,485,625],speed:1.13}],
['p8','Coastal Performance Engine',1200000,'Capacity 355 / 665 / 850 lb',{capacity:[355,665,850],speed:1.15}]]},
{id:'fuel',name:'Fuel',desc:'Increase the distance a MED-weight banner can fly.',nodes:[
['f1','Patched Fuel Tank',100,'MED range 5 miles',{range:5}],['f2','Larger Tank',300,'MED range 8 miles',{range:8}],['f3','New Fuel System',1000,'MED range 13 miles',{range:13}],['f4','Auxiliary Tank',4000,'MED range 22 miles',{range:22}],['f5','Extended Tank',15000,'MED range 35 miles',{range:35}],['f6','Long-Range Tank',60000,'MED range 55 miles',{range:55}],['f7','Extended Fuel System',250000,'MED range 85 miles',{range:85}],['f8','Endurance Fuel System',1000000,'MED range 130 miles',{range:130}]]},
{id:'efficiency',name:'Efficiency',desc:'Stretch each tank and reduce heavy-banner penalties.',nodes:[
['e1','Seal the Cowling',150,'5% less fuel used',{efficiency:.05}],['e2','Balance the Prop',500,'5% less fuel used',{efficiency:.05}],['e3','Streamlined Tow Cable',1500,'7% less fuel used',{efficiency:.07}],['e4','Weight Reduction',6000,'8% less fuel used',{efficiency:.08}],['e5','Cleaner Airframe',25000,'10% less fuel used',{efficiency:.10}],['e6','Cruise Tuning',100000,'12% less fuel used',{efficiency:.12}],['e7','Precision Fuel System',450000,'15% less fuel used',{efficiency:.15}]]},
{id:'advertising',name:'Advertising',desc:'Make more of the crowd notice every banner you tow.',nodes:[
['a1','Clean Banner Rig',125,'+5% people reached',{audience:.05}],['a2','Better Banner Position',450,'+7% people reached',{audience:.07}],['a3','Local Reputation',1800,'+8% people reached',{audience:.08}],['a4','Prime Tow Position',7500,'+10% people reached',{audience:.10}],['a5','Regional Reputation',30000,'+12% people reached',{audience:.12}],['a6','Premium Advertising',125000,'+15% people reached',{audience:.15}],['a7','National Reputation',600000,'+20% people reached',{audience:.20}]]}
];
const fresh=()=>({money:0,careerMiles:0,currentBeach:0,purchased:[],contract:null,offers:[],totalPeople:0,flights:0});
let state=load(),flight=null,lastTick=null,sceneryOffset=0,toastTimer=null;
const $=id=>document.getElementById(id);
const el={cash:$('cashValue'),career:$('careerMilesValue'),beach:$('beachValue'),contract:$('contractValue'),fuelText:$('fuelText'),fuelBar:$('fuelBar'),distance:$('distanceValue'),people:$('peopleValue'),earnings:$('flightEarningsValue'),min:$('minWeight'),med:$('medWeight'),max:$('maxWeight'),range:$('rangeEstimate'),flightButton:$('flightButton'),banner:$('banner'),zone:$('zoneName'),crowd:$('crowdRate'),contracts:$('contractsGrid'),active:$('activeContractCard'),refresh:$('refreshContractsButton'),tree:$('upgradeTree'),beaches:$('beachGrid'),upgradeCount:$('upgradeCount'),beachCount:$('beachCount'),sky:$('sky'),scenery:$('scenery'),toast:$('toast'),reset:$('resetButton')};
function load(){try{return {...fresh(),...JSON.parse(localStorage.getItem(SAVE)||'{}')}}catch{return fresh()}}
function save(){localStorage.setItem(SAVE,JSON.stringify(state))}
function cash(v){if(v<1000)return '$'+Math.round(v).toLocaleString();for(const [s,d] of [['T',1e12],['B',1e9],['M',1e6],['K',1e3]])if(v>=d)return '$'+(v/d).toFixed(v>=d*100?0:v>=d*10?1:2)+s;return '$'+Math.round(v).toLocaleString()}
const num=v=>Math.floor(v).toLocaleString();
const has=id=>state.purchased.includes(id);
function stats(){let capacity=[25,50,75],baseRange=3,speed=1,efficiency=0,audience=0;for(const b of branches)for(const n of b.nodes)if(has(n[0])){const e=n[4];if(e.capacity)capacity=e.capacity;if(e.range)baseRange=e.range;if(e.speed)speed*=e.speed;if(e.efficiency)efficiency+=e.efficiency;if(e.audience)audience+=e.audience}return{capacity,baseRange,speed,efficiency:Math.min(.62,efficiency),audience}}
function weightClass(w){const [min,med,max]=stats().capacity;if(w>max)return{key:'locked',label:'TOO HEAVY',fuel:Infinity};if(w<=min)return{key:'light',label:'LIGHT',fuel:.9};if(w<=med)return{key:'good',label:'MED — IDEAL',fuel:1};return{key:'heavy',label:'HEAVY',fuel:1.3}}
function rangeFor(w){const s=stats(),c=weightClass(w);return Number.isFinite(c.fuel)?s.baseRange/(c.fuel*(1-s.efficiency)):0}
const unlockedCount=()=>beaches.filter(b=>state.careerMiles>=b.unlock).length;
function stage(){const n=state.purchased.length;return n>=27?5:n>=21?4:n>=13?3:n>=6?2:1}
function offers(){if(state.contract||flight)return;const bi=state.currentBeach,b=beaches[bi],pool=names[bi],out=[],used=new Set();while(out.length<3){const ni=Math.floor(Math.random()*pool.length);if(used.has(ni))continue;used.add(ni);const weight=Math.round(b.weights[0]+(b.weights[1]-b.weights[0])*(.1+Math.random()*.82));const rate=b.rates[0]+(b.rates[1]-b.rates[0])*Math.random();const flights=3+Math.floor(Math.random()*Math.min(8,2+bi));out.push({id:`${Date.now()}_${ni}_${out.length}`,business:pool[ni],beachIndex:bi,weight:Math.max(b.weights[0],Math.min(b.weights[1],weight)),rate:+rate.toFixed(3),flightsTotal:flights,flightsRemaining:flights})}const max=stats().capacity[2];if(!out.some(o=>o.weight<=max))out[0].weight=Math.max(b.weights[0],Math.floor(max*.72));state.offers=out;save()}
function accept(id){if(state.contract||flight)return;const o=state.offers.find(x=>x.id===id);if(!o)return;if(weightClass(o.weight).key==='locked'){toast('That banner is above your current MAX tow weight.');return}state.contract={...o};state.offers=[];save();render();toast(`${o.business} contract accepted — ${o.flightsTotal} flights.`)}
function start(){if(!state.contract||flight)return;const r=rangeFor(state.contract.weight);if(!r)return;flight={distance:0,people:0,earnings:0,fuel:100,range:r};lastTick=performance.now();render();requestAnimationFrame(tick)}
function end(reason='ended'){if(!flight)return;const f=flight;flight=null;lastTick=null;const before=unlockedCount();state.money+=f.earnings;state.careerMiles+=f.distance;state.totalPeople+=f.people;state.flights++;if(state.contract){state.contract.flightsRemaining--;if(state.contract.flightsRemaining<=0){const business=state.contract.business;state.contract=null;offers();toast(`${business} contract complete. New offers are ready.`)}else toast(`${reason==='fuel'?'Fuel exhausted.':'Flight ended.'} ${state.contract.flightsRemaining} contract flight${state.contract.flightsRemaining===1?'':'s'} remaining.`)}const after=unlockedCount();if(after>before)toast(`${beaches[after-1].name} unlocked at ${num(beaches[after-1].unlock)} career miles!`);save();render()}
function tick(now){if(!flight)return;const dt=Math.min(.25,(now-lastTick)/1000);lastTick=now;const s=stats(),miles=.17*s.speed*dt;flight.distance+=miles;flight.fuel=Math.max(0,100*(1-flight.distance/flight.range));const b=beaches[state.currentBeach],zone=b.zones[Math.floor(flight.distance/.8)%b.zones.length],pulse=.88+Math.sin(now/850)*.09+Math.sin(now/2900)*.05,reached=miles*zone[1]*(1+s.audience)*pulse;flight.people+=Math.max(0,reached);flight.earnings=flight.people*state.contract.rate;sceneryOffset+=miles*48;moveScenery();renderFlight(zone);if(flight.fuel<=.001){end('fuel');return}setTimeout(()=>requestAnimationFrame(tick),TICK)}
function buy(id){if(flight)return;for(const b of branches){const i=b.nodes.findIndex(n=>n[0]===id);if(i<0)continue;const n=b.nodes[i];if(has(id)||i>0&&!has(b.nodes[i-1][0]))return;if(state.money<n[2]){toast(`You need ${cash(n[2]-state.money)} more.`);return}state.money-=n[2];state.purchased.push(id);save();render();toast(`${n[1]} installed.`);return}}
function travel(i){if(flight||state.contract){toast(state.contract?'Finish the current contract before changing beaches.':'End the flight before changing beaches.');return}if(state.careerMiles<beaches[i].unlock)return;state.currentBeach=i;state.offers=[];offers();save();buildScenery();render();toast(`Now advertising over ${beaches[i].name}.`)}
function renderTop(){const s=stats();el.cash.textContent=cash(state.money);el.career.textContent=state.careerMiles.toFixed(1)+' mi';el.beach.textContent=beaches[state.currentBeach].name;el.contract.textContent=state.contract?`${state.contract.business} (${state.contract.flightsRemaining}/${state.contract.flightsTotal})`:'None';el.min.textContent=s.capacity[0];el.med.textContent=s.capacity[1];el.max.textContent=s.capacity[2];el.range.textContent=`MED banner range: ${(s.baseRange/(1-s.efficiency)).toFixed(1)} mi`;el.upgradeCount.textContent=`${state.purchased.length}/30`;el.beachCount.textContent=`${unlockedCount()}/8`;el.sky.className=`sky stage-${stage()}`;el.banner.textContent=state.contract?state.contract.business.toUpperCase():'NO CONTRACT';if(flight){el.flightButton.textContent='End Flight — Counts as 1 Flight';el.flightButton.classList.add('danger');el.flightButton.disabled=false}else if(state.contract){el.flightButton.textContent=`Fly Contract (${state.contract.flightsRemaining} left)`;el.flightButton.classList.remove('danger');el.flightButton.disabled=false}else{el.flightButton.textContent='Choose a Contract';el.flightButton.classList.remove('danger');el.flightButton.disabled=true}}
function renderFlight(zoneOverride=null){const z=zoneOverride||beaches[state.currentBeach].zones[0];if(!flight){el.fuelText.textContent='100%';el.fuelBar.style.width='100%';el.distance.textContent='0.00 mi';el.people.textContent='0';el.earnings.textContent='$0'}else{el.fuelText.textContent=Math.ceil(flight.fuel)+'%';el.fuelBar.style.width=flight.fuel+'%';el.distance.textContent=flight.distance.toFixed(2)+' mi';el.people.textContent=num(flight.people);el.earnings.textContent=cash(flight.earnings)}el.zone.textContent=z[0];el.crowd.textContent=num(z[1])+' people / mile'}
function compact(v){return v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':num(v)}
function esc(t){return String(t).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderContracts(){if(!state.contract&&!state.offers.length)offers();el.refresh.disabled=!!(state.contract||flight);if(state.contract){const c=state.contract,w=weightClass(c.weight);el.active.classList.remove('hidden');el.active.innerHTML=`<div class="active-row"><div><h3>ACTIVE: ${esc(c.business)}</h3><p>${c.flightsRemaining} of ${c.flightsTotal} flights remaining · ${c.weight} lb banner · $${c.rate.toFixed(3)} per person</p></div><div><strong>${w.label}</strong><br><small>Estimated full-tank range ${rangeFor(c.weight).toFixed(1)} mi</small></div></div>`;el.contracts.innerHTML='';return}el.active.classList.add('hidden');el.active.innerHTML='';el.contracts.innerHTML=state.offers.map(c=>{const w=weightClass(c.weight),r=rangeFor(c.weight),b=beaches[c.beachIndex],reach=r*b.avg*(1+stats().audience);return `<article class="contract-card"><span class="contract-tag ${w.key}">${w.label}</span><h3>${esc(c.business)}</h3><div class="contract-stats"><div class="contract-stat"><span>Banner</span><strong>${c.weight} lb</strong></div><div class="contract-stat"><span>Pay</span><strong>$${c.rate.toFixed(3)}/person</strong></div><div class="contract-stat"><span>Length</span><strong>${c.flightsTotal} flights</strong></div><div class="contract-stat"><span>Est. Reach</span><strong>${w.key==='locked'?'—':compact(reach)}</strong></div></div><small>${w.key==='heavy'?'Higher fuel burn. Better pay may still make it worthwhile.':w.key==='locked'?'Upgrade Power to tow this banner.':w.key==='light'?'Easy tow with slightly better range.':'Inside your ideal tow range.'}</small><button class="contract-button" data-contract="${c.id}" ${w.key==='locked'?'disabled':''}>Accept Contract</button></article>`}).join('');document.querySelectorAll('[data-contract]').forEach(b=>b.addEventListener('click',()=>accept(b.dataset.contract)))}
function renderTree(){el.tree.innerHTML=branches.map(b=>`<section class="upgrade-branch"><h3>${b.name}</h3><p>${b.desc}</p>${b.nodes.map((n,i)=>{const owned=has(n[0]),available=i===0||has(b.nodes[i-1][0]),status=owned?'purchased':available?'available':'locked';return `<div class="upgrade-node ${status}"><h4>${i+1}. ${n[1]}</h4><p>${n[3]}</p><button class="upgrade-button" data-upgrade="${n[0]}" ${owned||!available||flight?'disabled':''}>${owned?'Installed':available?cash(n[2]):'Locked'}</button></div>`}).join('')}</section>`).join('');document.querySelectorAll('[data-upgrade]').forEach(b=>b.addEventListener('click',()=>buy(b.dataset.upgrade)))}
function renderBeaches(){el.beaches.innerHTML=beaches.map((b,i)=>{const unlocked=state.careerMiles>=b.unlock,current=i===state.currentBeach,prev=i?beaches[i-1].unlock:0,progress=unlocked?100:Math.max(0,Math.min(100,((state.careerMiles-prev)/(b.unlock-prev))*100));return `<article class="beach-card ${current?'current':''} ${unlocked?'':'locked'}"><span class="beach-number">Beach ${i+1} of 8</span><h3>${b.name}</h3><p>${b.desc}</p><div class="beach-details"><span><strong>Avg crowd:</strong> ${num(b.avg)} / mile</span><span><strong>Unlock:</strong> ${num(b.unlock)} career miles</span></div>${unlocked?'':`<div class="progress-track"><div style="width:${progress}%"></div></div><small>${state.careerMiles.toFixed(1)} / ${num(b.unlock)} mi</small>`}<button class="beach-button" data-beach="${i}" ${!unlocked||current||flight||state.contract?'disabled':''}>${current?'Current Beach':unlocked?'Fly Here':'Locked'}</button></article>`}).join('');document.querySelectorAll('[data-beach]').forEach(b=>b.addEventListener('click',()=>travel(+b.dataset.beach)))}
function render(){renderTop();renderFlight();renderContracts();renderTree();renderBeaches()}
function toast(msg){clearTimeout(toastTimer);el.toast.textContent=msg;el.toast.classList.add('show');toastTimer=setTimeout(()=>el.toast.classList.remove('show'),2800)}
function buildScenery(){const bi=state.currentBeach,d=Math.min(12,4+bi),items=[];for(let i=0;i<d;i++){const left=3+i/d*96;if((i+bi)%5===0)items.push(`<div class="pier" style="left:${left}%"></div>`);else if((i+bi)%3===0)items.push(`<div class="palm" style="left:${left}%;height:${42+i%4*9}px"></div>`);else items.push(`<div class="building" style="left:${left}%;height:${45+bi*10+(i*17)%70}px;width:${38+i%3*11}px"></div>`)}el.scenery.innerHTML=items.join('')}
function moveScenery(){const items=el.scenery.children;for(let i=0;i<items.length;i++){const base=i/Math.max(1,items.length)*110,x=((base-sceneryOffset*.09)%120+120)%120-10;items[i].style.left=x+'%'}}
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t===tab));document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active-panel'));$(tab.dataset.tab+'Panel').classList.add('active-panel')}));
el.flightButton.addEventListener('click',()=>flight?end('ended'):start());el.refresh.addEventListener('click',()=>{if(state.contract||flight)return;state.offers=[];offers();renderContracts()});el.reset.addEventListener('click',()=>{if(!confirm('Reset all Banner Miles progress on this device?'))return;localStorage.removeItem(SAVE);state=fresh();flight=null;offers();buildScenery();render();toast('Save reset.')});
offers();buildScenery();render();
})();
